/*
 * SimpleInventoryAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using SimpleInventoryAPI.Standard.Controllers;
using SimpleInventoryAPI.Standard.Http.Client;
using SimpleInventoryAPI.Standard.Utilities;

namespace SimpleInventoryAPI.Standard
{
    public partial class SimpleInventoryAPIClient
    {

        /// <summary>
        /// Singleton access to Developers controller
        /// </summary>
        public DevelopersController Developers
        {
            get
            {
                return DevelopersController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Admins controller
        /// </summary>
        public AdminsController Admins
        {
            get
            {
                return AdminsController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        #region Constructors
        /// <summary>
        /// Default constructor
        /// </summary>
        public SimpleInventoryAPIClient() { }
        #endregion
    }
}