/*
 * SimpleInventoryAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SimpleInventoryAPI.Standard;
using SimpleInventoryAPI.Standard.Utilities;


namespace SimpleInventoryAPI.Standard.Models
{
    public class InventoryItem : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Guid id;
        private string name;
        private DateTime releaseDate;
        private Models.Manufacturer manufacturer;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("id")]
        public Guid Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("releaseDate")]
        public DateTime ReleaseDate 
        { 
            get 
            {
                return this.releaseDate; 
            } 
            set 
            {
                this.releaseDate = value;
                onPropertyChanged("ReleaseDate");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("manufacturer")]
        public Models.Manufacturer Manufacturer 
        { 
            get 
            {
                return this.manufacturer; 
            } 
            set 
            {
                this.manufacturer = value;
                onPropertyChanged("Manufacturer");
            }
        }
    }
} 