/*
 * SimpleInventoryAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json.Converters;
using SimpleInventoryAPI.Standard;
using SimpleInventoryAPI.Standard.Utilities;
using SimpleInventoryAPI.Standard.Http.Request;
using SimpleInventoryAPI.Standard.Http.Response;
using SimpleInventoryAPI.Standard.Http.Client;
using SimpleInventoryAPI.Standard.Exceptions;

namespace SimpleInventoryAPI.Standard.Controllers
{
    public partial class AdminsController: BaseController
    {
        #region Singleton Pattern

        //private static variables for the singleton pattern
        private static object syncObject = new object();
        private static AdminsController instance = null;

        /// <summary>
        /// Singleton pattern implementation
        /// </summary>
        internal static AdminsController Instance
        {
            get
            {
                lock (syncObject)
                {
                    if (null == instance)
                    {
                        instance = new AdminsController();
                    }
                }
                return instance;
            }
        }

        #endregion Singleton Pattern

        /// <summary>
        /// Adds an item to the system
        /// </summary>
        /// <param name="body">Optional parameter: Inventory item to add</param>
        /// <return>Returns the void response from the API call</return>
        public void AddInventory(Models.InventoryItem body = null)
        {
            Task t = AddInventoryAsync(body);
            APIHelper.RunTaskSynchronously(t);
        }

        /// <summary>
        /// Adds an item to the system
        /// </summary>
        /// <param name="body">Optional parameter: Inventory item to add</param>
        /// <return>Returns the void response from the API call</return>
        public async Task AddInventoryAsync(Models.InventoryItem body = null)
        {
            //the base uri for api requests
            string _baseUri = Configuration.BaseUri;

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/inventory");


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" },
                { "content-type", "application/json; charset=utf-8" }
            };

            //append body params
            var _body = APIHelper.JsonSerialize(body);

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.PostBody(_queryUrl, _headers, _body);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request,_response);

            //Error handling using HTTP status codes
            if (_response.StatusCode == 400)
                throw new APIException(@"invalid input, object invalid", _context);

            if (_response.StatusCode == 409)
                throw new APIException(@"an existing item already exists", _context);

            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

        }

    }
} 