/*
 * SimpleInventoryAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json.Converters;
using SimpleInventoryAPI.Standard;
using SimpleInventoryAPI.Standard.Utilities;
using SimpleInventoryAPI.Standard.Http.Request;
using SimpleInventoryAPI.Standard.Http.Response;
using SimpleInventoryAPI.Standard.Http.Client;
using SimpleInventoryAPI.Standard.Exceptions;

namespace SimpleInventoryAPI.Standard.Controllers
{
    public partial class DevelopersController: BaseController
    {
        #region Singleton Pattern

        //private static variables for the singleton pattern
        private static object syncObject = new object();
        private static DevelopersController instance = null;

        /// <summary>
        /// Singleton pattern implementation
        /// </summary>
        internal static DevelopersController Instance
        {
            get
            {
                lock (syncObject)
                {
                    if (null == instance)
                    {
                        instance = new DevelopersController();
                    }
                }
                return instance;
            }
        }

        #endregion Singleton Pattern

        /// <summary>
        /// By passing in the appropriate options, you can search for
        /// available inventory in the system
        /// </summary>
        /// <param name="searchString">Optional parameter: pass an optional search string for looking up inventory</param>
        /// <param name="skip">Optional parameter: number of records to skip for pagination</param>
        /// <param name="limit">Optional parameter: maximum number of records to return</param>
        /// <return>Returns the List<Models.InventoryItem> response from the API call</return>
        public List<Models.InventoryItem> SearchInventory(string searchString = null, int? skip = null, int? limit = null)
        {
            Task<List<Models.InventoryItem>> t = SearchInventoryAsync(searchString, skip, limit);
            APIHelper.RunTaskSynchronously(t);
            return t.Result;
        }

        /// <summary>
        /// By passing in the appropriate options, you can search for
        /// available inventory in the system
        /// </summary>
        /// <param name="searchString">Optional parameter: pass an optional search string for looking up inventory</param>
        /// <param name="skip">Optional parameter: number of records to skip for pagination</param>
        /// <param name="limit">Optional parameter: maximum number of records to return</param>
        /// <return>Returns the List<Models.InventoryItem> response from the API call</return>
        public async Task<List<Models.InventoryItem>> SearchInventoryAsync(string searchString = null, int? skip = null, int? limit = null)
        {
            //the base uri for api requests
            string _baseUri = Configuration.BaseUri;

            //prepare query string for API call
            StringBuilder _queryBuilder = new StringBuilder(_baseUri);
            _queryBuilder.Append("/inventory");

            //process optional query parameters
            APIHelper.AppendUrlWithQueryParameters(_queryBuilder, new Dictionary<string, object>()
            {
                { "searchString", searchString },
                { "skip", skip },
                { "limit", limit }
            },ArrayDeserializationFormat,ParameterSeparator);


            //validate and preprocess url
            string _queryUrl = APIHelper.CleanUrl(_queryBuilder);

            //append request with appropriate headers and parameters
            var _headers = new Dictionary<string,string>()
            {
                { "user-agent", "APIMATIC 2.0" },
                { "accept", "application/json" }
            };

            //prepare the API call request to fetch the response
            HttpRequest _request = ClientInstance.Get(_queryUrl,_headers);

            //invoke request and get response
            HttpStringResponse _response = (HttpStringResponse) await ClientInstance.ExecuteAsStringAsync(_request).ConfigureAwait(false);
            HttpContext _context = new HttpContext(_request,_response);

            //Error handling using HTTP status codes
            if (_response.StatusCode == 400)
                throw new APIException(@"bad input parameter", _context);

            //handle errors defined at the API level
            base.ValidateResponse(_response, _context);

            try
            {
                return APIHelper.JsonDeserialize<List<Models.InventoryItem>>(_response.Body);
            }
            catch (Exception _ex)
            {
                throw new APIException("Failed to parse the response: " + _ex.Message, _context);
            }
        }

    }
} 