/*
 * SimpleInventoryAPI.Tests
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Threading.Tasks;
using Newtonsoft.Json.Converters;
using SimpleInventoryAPI.Standard;
using SimpleInventoryAPI.Standard.Utilities; 
using SimpleInventoryAPI.Standard.Http.Client;
using SimpleInventoryAPI.Standard.Http.Response;
using SimpleInventoryAPI.Tests.Helpers;
using NUnit.Framework;
using SimpleInventoryAPI.Standard;
using SimpleInventoryAPI.Standard.Controllers;
using SimpleInventoryAPI.Standard.Exceptions;

namespace SimpleInventoryAPI.Tests
{
    [TestFixture]
    public class AdminsControllerTest : ControllerTestBase
    {
        /// <summary>
        /// Controller instance (for all tests)
        /// </summary>
        private static AdminsController controller;

        /// <summary>
        /// Setup test class
        /// </summary>
        [SetUp]
        public static void SetUpClass()
        {
            controller = GetClient().Admins;
        }

        /// <summary>
        /// Adds an item to the system 
        /// </summary>
        [Test]
        public async Task TestTestAddInventory() 
        {
            // Parameters for the API call
            Standard.Models.InventoryItem body = null;

            // Perform API call

            try
            {
                await controller.AddInventoryAsync(body);
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(201, httpCallBackHandler.Response.StatusCode,
                    "Status should be 201");

        }

    }
}