/*
 * SimpleInventoryAPI.Tests
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Threading.Tasks;
using Newtonsoft.Json.Converters;
using SimpleInventoryAPI.Standard;
using SimpleInventoryAPI.Standard.Utilities; 
using SimpleInventoryAPI.Standard.Http.Client;
using SimpleInventoryAPI.Standard.Http.Response;
using SimpleInventoryAPI.Tests.Helpers;
using NUnit.Framework;
using SimpleInventoryAPI.Standard;
using SimpleInventoryAPI.Standard.Controllers;
using SimpleInventoryAPI.Standard.Exceptions;

namespace SimpleInventoryAPI.Tests
{
    [TestFixture]
    public class DevelopersControllerTest : ControllerTestBase
    {
        /// <summary>
        /// Controller instance (for all tests)
        /// </summary>
        private static DevelopersController controller;

        /// <summary>
        /// Setup test class
        /// </summary>
        [SetUp]
        public static void SetUpClass()
        {
            controller = GetClient().Developers;
        }

        /// <summary>
        /// By passing in the appropriate options, you can search for
        ///available inventory in the system
        /// 
        /// </summary>
        [Test]
        public async Task TestTestSearchInventory() 
        {
            // Parameters for the API call
            string searchString = null;
            int? skip = null;
            int? limit = null;

            // Perform API call
            List<Standard.Models.InventoryItem> result = null;

            try
            {
                result = await controller.SearchInventoryAsync(searchString, skip, limit);
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

            // Test headers
            Dictionary<string, string> headers = new Dictionary<string, string>();
            headers.Add("Content-Type", "application/json");

            Assert.IsTrue(TestHelper.AreHeadersProperSubsetOf (
                    headers, httpCallBackHandler.Response.Headers),
                    "Headers should match");

        }

    }
}